### ISSUE TITLE
Build OSS wcnss_service, or move blob to /system/bin for compatibility

### ISSUE THREAD

**Issue by stellirin** [sonyxperiadev/device-sony-yukon#157]
Lots of projects provide an open source wcnss_service. If we want to build yukon on that project we need to either modify the project to remove their OSS implementation or remove ours from the blob zip.

But actually if we can see OSS versions everywhere, why not just remove the blob and build our own?

https://github.com/AdFad666/wcnss-service

Working on Firefox OS, I'll test soon on AOSP.

**Comment by jerpelea** [comment]
If it works push it to device github!

**Comment by jerpelea** [comment]
is this wcnss service working fine on AOSP?
