### ISSUE TITLE
The internal SD card (internal storage) is not mounted

### ISSUE THREAD

**Issue by gtrentalancia** [sonyxperiadev/device-sony-yukon#218]
The internal SD card (internal storage) is not mounted correctly at system bootup.

**Comment by gtrentalancia** [comment]
Fixed here (KitKat branch):

https://github.com/sonyxperiadev/device-sony-yukon/pull/215/commits/03c305d83cbd175b15bf326c26a746c228b1a909

**Comment by gtrentalancia** [comment]
Why have you closed this issue without merging the above mentioned fix ?

**Comment by jerpelea** [comment]
I will merge it after you push on the proper branch

**Comment by gtrentalancia** [comment]
I have double-checked and the branch mentioned in the official Sony instructions is kk_mr2:

https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-kitkat-for-unlocked-xperia-devices/
