### ISSUE TITLE
It is not possible to route audio to the loudspeaker during a voice call

### ISSUE THREAD

**Issue by gtrentalancia** [sonyxperiadev/device-sony-yukon#219]
On KitKat (branch kk_mr2) it is not possible to use the loudspeaker during a voice call.

The code in packages/services/Telephony/src/com/android/phone/PhoneUtils.java correctly calls AudioManager.setSpeakerphoneOn(), but unfortunately the audio is not routed correctly to the speaker.

Calling AudioManager.setMode(AudioManager.MODE_IN_CALL) before calling AudioManager.setSpeakerphoneOn(), as suggested in some related discussions, does not sort the issue.

There is no anomaly shown in the logcat output.

**Comment by jerpelea** [comment]
you should update the mixer.xml

**Comment by gtrentalancia** [comment]
Thanks very much for your tip, it works !

Solved by updating both /system/etc/audio_policy.conf and /system/etc/mixer_paths.xml

**Comment by gtrentalancia** [comment]
I have double-checked. Only /system/etc/mixer_paths.xml needs to be updated.

Thanks again.
